module.exports = [
	{ value : "3MINDIA", label : "3M India Ltd."},
	{ value : "ABB", label : "ABB India Ltd."},
	{ value : "ACC", label : "ACC Ltd."},
	{ value : "AIAENG", label : "AIA Engineering Ltd."},
	{ value : "APLAPOLLO", label : "APL Apollo Tubes Ltd."},
	{ value : "AUBANK", label : "AU Small Finance Bank Ltd."},
	{ value : "AARTIDRUGS", label : "Aarti Drugs Ltd."},
	{ value : "AAVAS", label : "Aavas Financiers Ltd."},
	{ value : "ABBOTINDIA", label : "Abbott India Ltd."},
	{ value : "ADANIENT", label : "Adani Enterprises Ltd."},
	{ value : "ADANIGREEN", label : "Adani Green Energy Ltd."},
	{ value : "ADANIPORTS", label : "Adani Ports and Special Economic Zone Ltd."},
	{ value : "ATGL", label : "Adani Total Gas Ltd."},
	{ value : "ADANITRANS", label : "Adani Transmission Ltd."},
	{ value : "ABCAPITAL", label : "Aditya Birla Capital Ltd."},
	{ value : "ABFRL", label : "Aditya Birla Fashion and Retail Ltd."},
	{ value : "ABSLAMC", label : "Aditya Birla Sun Life AMC Ltd."},
	{ value : "ADVENZYMES", label : "Advanced Enzyme Tech Ltd."},
	{ value : "AEGISCHEM", label : "Aegis Logistics Ltd."},
	{ value : "AFFLE", label : "Affle (India) Ltd."},
	{ value : "AJANTPHARM", label : "Ajanta Pharmaceuticals Ltd."},
	{ value : "APLLTD", label : "Alembic Pharmaceuticals Ltd."},
	{ value : "ALKEM", label : "Alkem Laboratories Ltd."},
	{ value : "ALKYLAMINE", label : "Alkyl Amines Chemicals Ltd."},
	{ value : "ALLCARGO", label : "Allcargo Logistics Ltd."},
	{ value : "ALOKINDS", label : "Alok Industries Ltd."},
	{ value : "AMARAJABAT", label : "Amara Raja Batteries Ltd."},
	{ value : "AMBER", label : "Amber Enterprises India Ltd."},
	{ value : "AMBUJACEM", label : "Ambuja Cements Ltd."},
	{ value : "ANGELONE", label : "Angel One Ltd."},
	{ value : "ANURAS", label : "Anupam Rasayan India Ltd."},
	{ value : "APOLLOHOSP", label : "Apollo Hospitals Enterprise Ltd."},
	{ value : "APOLLOTYRE", label : "Apollo Tyres Ltd."},
	{ value : "APTUS", label : "Aptus Value Housing Finance India Ltd."},
	{ value : "ASAHIINDIA", label : "Asahi India Glass Ltd."},
	{ value : "ASHOKLEY", label : "Ashok Leyland Ltd."},
	{ value : "ASIANPAINT", label : "Asian Paints Ltd."},
	{ value : "ASTERDM", label : "Aster DM Healthcare Ltd."},
	{ value : "ASTRAZEN", label : "AstraZenca Pharma India Ltd."},
	{ value : "ASTRAL", label : "Astral Ltd."},
	{ value : "ATUL", label : "Atul Ltd."},
	{ value : "AUROPHARMA", label : "Aurobindo Pharma Ltd."},
	{ value : "AVANTIFEED", label : "Avanti Feeds Ltd."},
	{ value : "DMART", label : "Avenue Supermarts Ltd."},
	{ value : "AXISBANK", label : "Axis Bank Ltd."},
	{ value : "BASF", label : "BASF India Ltd."},
	{ value : "BSE", label : "BSE Ltd."},
	{ value : "BAJAJ-AUTO", label : "Bajaj Auto Ltd."},
	{ value : "BAJAJELEC", label : "Bajaj Electricals Ltd"},
	{ value : "BAJFINANCE", label : "Bajaj Finance Ltd."},
	{ value : "BAJAJFINSV", label : "Bajaj Finserv Ltd."},
	{ value : "BAJAJHLDNG", label : "Bajaj Holdings & Investment Ltd."},
	{ value : "BALAMINES", label : "Balaji Amines Ltd."},
	{ value : "BALKRISIND", label : "Balkrishna Industries Ltd."},
	{ value : "BALRAMCHIN", label : "Balrampur Chini Mills Ltd."},
	{ value : "BANDHANBNK", label : "Bandhan Bank Ltd."},
	{ value : "BANKBARODA", label : "Bank of Baroda"},
	{ value : "BANKINDIA", label : "Bank of India"},
	{ value : "MAHABANK", label : "Bank of Maharashtra"},
	{ value : "BATAINDIA", label : "Bata India Ltd."},
	{ value : "BAYERCROP", label : "Bayer Cropscience Ltd."},
	{ value : "BERGEPAINT", label : "Berger Paints India Ltd."},
	{ value : "BDL", label : "Bharat Dynamics Ltd."},
	{ value : "BEL", label : "Bharat Electronics Ltd."},
	{ value : "BHARATFORG", label : "Bharat Forge Ltd."},
	{ value : "BHEL", label : "Bharat Heavy Electricals Ltd."},
	{ value : "BPCL", label : "Bharat Petroleum Corporation Ltd."},
	{ value : "BHARTIARTL", label : "Bharti Airtel Ltd."},
	{ value : "BIOCON", label : "Biocon Ltd."},
	{ value : "BIRLACORPN", label : "Birla Corporation Ltd."},
	{ value : "BSOFT", label : "Birlasoft Ltd."},
	{ value : "BLUEDART", label : "Blue Dart Express Ltd."},
	{ value : "BLUESTARCO", label : "Blue Star Ltd."},
	{ value : "BBTC", label : "Bombay Burmah Trading Corporation Ltd."},
	{ value : "BORORENEW", label : "Borosil Renewables Ltd."},
	{ value : "BOSCHLTD", label : "Bosch Ltd."},
	{ value : "BRIGADE", label : "Brigade Enterprises Ltd."},
	{ value : "BCG", label : "Brightcom Group Ltd."},
	{ value : "BRITANNIA", label : "Britannia Industries Ltd."},
	{ value : "MAPMYINDIA", label : "C.E. Info Systems Ltd."},
	{ value : "CCL", label : "CCL Products (I) Ltd."},
	{ value : "CESC", label : "CESC Ltd."},
	{ value : "CGPOWER", label : "CG Power and Industrial Solutions Ltd."},
	{ value : "CRISIL", label : "CRISIL Ltd."},
	{ value : "CSBBANK", label : "CSB Bank Ltd."},
	{ value : "CANFINHOME", label : "Can Fin Homes Ltd."},
	{ value : "CANBK", label : "Canara Bank"},
	{ value : "CAPLIPOINT", label : "Caplin Point Laboratories Ltd."},
	{ value : "CGCL", label : "Capri Global Capital Ltd."},
	{ value : "CARBORUNIV", label : "Carborundum Universal Ltd."},
	{ value : "CASTROLIND", label : "Castrol India Ltd."},
	{ value : "CEATLTD", label : "Ceat Ltd."},
	{ value : "CENTRALBK", label : "Central Bank of India"},
	{ value : "CDSL", label : "Central Depository Services (India) Ltd."},
	{ value : "CENTURYPLY", label : "Century Plyboards (India) Ltd."},
	{ value : "CENTURYTEX", label : "Century Textile & Industries Ltd."},
	{ value : "CERA", label : "Cera Sanitaryware Ltd"},
	{ value : "CHALET", label : "Chalet Hotels Ltd."},
	{ value : "CHAMBLFERT", label : "Chambal Fertilizers & Chemicals Ltd."},
	{ value : "CHEMPLASTS", label : "Chemplast Sanmar Ltd."},
	{ value : "CHOLAHLDNG", label : "Cholamandalam Financial Holdings Ltd."},
	{ value : "CHOLAFIN", label : "Cholamandalam Investment and Finance Company Ltd."},
	{ value : "CIPLA", label : "Cipla Ltd."},
	{ value : "CUB", label : "City Union Bank Ltd."},
	{ value : "CLEAN", label : "Clean Science and Technology Ltd."},
	{ value : "COALINDIA", label : "Coal India Ltd."},
	{ value : "COCHINSHIP", label : "Cochin Shipyard Ltd."},
	{ value : "COFORGE", label : "Coforge Ltd."},
	{ value : "COLPAL", label : "Colgate Palmolive (India) Ltd."},
	{ value : "CAMS", label : "Computer Age Management Services Ltd."},
	{ value : "CONCOR", label : "Container Corporation of India Ltd."},
	{ value : "COROMANDEL", label : "Coromandel International Ltd."},
	{ value : "CREDITACC", label : "CreditAccess Grameen Ltd."},
	{ value : "CROMPTON", label : "Crompton Greaves Consumer Electricals Ltd."},
	{ value : "CUMMINSIND", label : "Cummins India Ltd."},
	{ value : "CYIENT", label : "Cyient Ltd."},
	{ value : "DCMSHRIRAM", label : "DCM Shriram Ltd."},
	{ value : "DLF", label : "DLF Ltd."},
	{ value : "DABUR", label : "Dabur India Ltd."},
	{ value : "DALBHARAT", label : "Dalmia Bharat Ltd."},
	{ value : "DEEPAKNTR", label : "Deepak Nitrite Ltd."},
	{ value : "DELTACORP", label : "Delta Corp Ltd."},
	{ value : "DEVYANI", label : "Devyani International Ltd."},
	{ value : "DHANI", label : "Dhani Services Ltd."},
	{ value : "DBL", label : "Dilip Buildcon Ltd."},
	{ value : "DIVISLAB", label : "Divi's Laboratories Ltd."},
	{ value : "DIXON", label : "Dixon Technologies (India) Ltd."},
	{ value : "LALPATHLAB", label : "Dr. Lal Path Labs Ltd."},
	{ value : "DRREDDY", label : "Dr. Reddy's Laboratories Ltd."},
	{ value : "EIDPARRY", label : "E.I.D. Parry (India) Ltd."},
	{ value : "EIHOTEL", label : "EIH Ltd."},
	{ value : "EPL", label : "EPL Ltd."},
	{ value : "EASEMYTRIP", label : "Easy Trip Planners Ltd."},
	{ value : "EDELWEISS", label : "Edelweiss Financial Services Ltd."},
	{ value : "EICHERMOT", label : "Eicher Motors Ltd."},
	{ value : "ELGIEQUIP", label : "Elgi Equipments Ltd."},
	{ value : "EMAMILTD", label : "Emami Ltd."},
	{ value : "ENDURANCE", label : "Endurance Technologies Ltd."},
	{ value : "ENGINERSIN", label : "Engineers India Ltd."},
	{ value : "EQUITAS", label : "Equitas Holdings Ltd."},
	{ value : "EQUITASBNK", label : "Equitas Small Finance Bank Ltd."},
	{ value : "ERIS", label : "Eris Lifesciences Ltd."},
	{ value : "ESCORTS", label : "Escorts Kubota Ltd."},
	{ value : "EXIDEIND", label : "Exide Industries Ltd."},
	{ value : "FDC", label : "FDC Ltd."},
	{ value : "NYKAA", label : "FSN E-Commerce Ventures Ltd."},
	{ value : "FEDERALBNK", label : "Federal Bank Ltd."},
	{ value : "FACT", label : "Fertilisers and Chemicals Travancore Ltd."},
	{ value : "FINEORG", label : "Fine Organic Industries Ltd."},
	{ value : "FINCABLES", label : "Finolex Cables Ltd."},
	{ value : "FINPIPE", label : "Finolex Industries Ltd."},
	{ value : "FSL", label : "Firstsource Solutions Ltd."},
	{ value : "FORTIS", label : "Fortis Healthcare Ltd."},
	{ value : "GRINFRA", label : "G R Infraprojects Ltd."},
	{ value : "GAIL", label : "GAIL (India) Ltd."},
	{ value : "GMMPFAUDLR", label : "GMM Pfaudler Ltd."},
	{ value : "GMRINFRA", label : "GMR Infrastructure Ltd."},
	{ value : "GALAXYSURF", label : "Galaxy Surfactants Ltd."},
	{ value : "GARFIBRES", label : "Garware Technical Fibres Ltd."},
	{ value : "GICRE", label : "General Insurance Corporation of India"},
	{ value : "GLAND", label : "Gland Pharma Ltd."},
	{ value : "GLAXO", label : "Glaxosmithkline Pharmaceuticals Ltd."},
	{ value : "GLS", label : "Glenmark Life Sciences Ltd."},
	{ value : "GLENMARK", label : "Glenmark Pharmaceuticals Ltd."},
	{ value : "GOCOLORS", label : "Go Fashion (India) Ltd."},
	{ value : "GODFRYPHLP", label : "Godfrey Phillips India Ltd."},
	{ value : "GODREJAGRO", label : "Godrej Agrovet Ltd."},
	{ value : "GODREJCP", label : "Godrej Consumer Products Ltd."},
	{ value : "GODREJIND", label : "Godrej Industries Ltd."},
	{ value : "GODREJPROP", label : "Godrej Properties Ltd."},
	{ value : "GRANULES", label : "Granules India Ltd."},
	{ value : "GRAPHITE", label : "Graphite India Ltd."},
	{ value : "GRASIM", label : "Grasim Industries Ltd."},
	{ value : "GESHIP", label : "Great Eastern Shipping Co. Ltd."},
	{ value : "GRINDWELL", label : "Grindwell Norton Ltd."},
	{ value : "GUJALKALI", label : "Gujarat Alkalies & Chemicals Ltd."},
	{ value : "GAEL", label : "Gujarat Ambuja Exports Ltd."},
	{ value : "FLUOROCHEM", label : "Gujarat Fluorochemicals Ltd."},
	{ value : "GUJGASLTD", label : "Gujarat Gas Ltd."},
	{ value : "GNFC", label : "Gujarat Narmada Valley Fertilizers and Chemicals Ltd."},
	{ value : "GPPL", label : "Gujarat Pipavav Port Ltd."},
	{ value : "GSFC", label : "Gujarat State Fertilizers & Chemicals Ltd."},
	{ value : "GSPL", label : "Gujarat State Petronet Ltd."},
	{ value : "HEG", label : "H.E.G. Ltd."},
	{ value : "HCLTECH", label : "HCL Technologies Ltd."},
	{ value : "HDFCAMC", label : "HDFC Asset Management Company Ltd."},
	{ value : "HDFCBANK", label : "HDFC Bank Ltd."},
	{ value : "HDFCLIFE", label : "HDFC Life Insurance Company Ltd."},
	{ value : "HFCL", label : "HFCL Ltd."},
	{ value : "HLEGLAS", label : "HLE Glascoat Ltd."},
	{ value : "HAPPSTMNDS", label : "Happiest Minds Technologies Ltd."},
	{ value : "HATHWAY", label : "Hathway Cable & Datacom Ltd."},
	{ value : "HATSUN", label : "Hatsun Agro Product Ltd."},
	{ value : "HAVELLS", label : "Havells India Ltd."},
	{ value : "HEMIPROP", label : "Hemisphere Properties India Ltd."},
	{ value : "HEROMOTOCO", label : "Hero MotoCorp Ltd."},
	{ value : "HIKAL", label : "Hikal Ltd."},
	{ value : "HINDALCO", label : "Hindalco Industries Ltd."},
	{ value : "HGS", label : "Hinduja Global Solutions Ltd."},
	{ value : "HAL", label : "Hindustan Aeronautics Ltd."},
	{ value : "HINDCOPPER", label : "Hindustan Copper Ltd."},
	{ value : "HINDPETRO", label : "Hindustan Petroleum Corporation Ltd."},
	{ value : "HINDUNILVR", label : "Hindustan Unilever Ltd."},
	{ value : "HINDZINC", label : "Hindustan Zinc Ltd."},
	{ value : "POWERINDIA", label : "Hitachi Energy India Ltd."},
	{ value : "HOMEFIRST", label : "Home First Finance Company India Ltd."},
	{ value : "HONAUT", label : "Honeywell Automation India Ltd."},
	{ value : "HUDCO", label : "Housing & Urban Development Corporation Ltd."},
	{ value : "HDFC", label : "Housing Development Finance Corporation Ltd."},
	{ value : "ICICIBANK", label : "ICICI Bank Ltd."},
	{ value : "ICICIGI", label : "ICICI Lombard General Insurance Company Ltd."},
	{ value : "ICICIPRULI", label : "ICICI Prudential Life Insurance Company Ltd."},
	{ value : "ISEC", label : "ICICI Securities Ltd."},
	{ value : "IDBI", label : "IDBI Bank Ltd."},
	{ value : "IDFCFIRSTB", label : "IDFC First Bank Ltd."},
	{ value : "IDFC", label : "IDFC Ltd."},
	{ value : "IFBIND", label : "IFB Industries Ltd."},
	{ value : "IIFL", label : "IIFL Finance Ltd."},
	{ value : "IIFLWAM", label : "IIFL Wealth Management Ltd."},
	{ value : "IRB", label : "IRB Infrastructure Developers Ltd."},
	{ value : "IRCON", label : "IRCON International Ltd."},
	{ value : "ITC", label : "ITC Ltd."},
	{ value : "ITI", label : "ITI Ltd."},
	{ value : "INDIACEM", label : "India Cements Ltd."},
	{ value : "IBULHSGFIN", label : "Indiabulls Housing Finance Ltd."},
	{ value : "IBREALEST", label : "Indiabulls Real Estate Ltd."},
	{ value : "INDIAMART", label : "Indiamart Intermesh Ltd."},
	{ value : "INDIANB", label : "Indian Bank"},
	{ value : "IEX", label : "Indian Energy Exchange Ltd."},
	{ value : "INDHOTEL", label : "Indian Hotels Co. Ltd."},
	{ value : "IOC", label : "Indian Oil Corporation Ltd."},
	{ value : "IOB", label : "Indian Overseas Bank"},
	{ value : "IRCTC", label : "Indian Railway Catering And Tourism Corporation Ltd."},
	{ value : "IRFC", label : "Indian Railway Finance Corporation Ltd."},
	{ value : "INDIGOPNTS", label : "Indigo Paints Ltd."},
	{ value : "ICIL", label : "Indo Count Industries Ltd."},
	{ value : "INDOCO", label : "Indoco Remedies Ltd."},
	{ value : "IGL", label : "Indraprastha Gas Ltd."},
	{ value : "INDUSTOWER", label : "Indus Towers Ltd."},
	{ value : "INDUSINDBK", label : "IndusInd Bank Ltd."},
	{ value : "INFIBEAM", label : "Infibeam Avenues Ltd."},
	{ value : "NAUKRI", label : "Info Edge (India) Ltd."},
	{ value : "INFY", label : "Infosys Ltd."},
	{ value : "INOXLEISUR", label : "Inox Leisure Ltd."},
	{ value : "INTELLECT", label : "Intellect Design Arena Ltd."},
	{ value : "INDIGO", label : "InterGlobe Aviation Ltd."},
	{ value : "IPCALAB", label : "Ipca Laboratories Ltd."},
	{ value : "JBCHEPHARM", label : "J.B. Chemicals & Pharmaceuticals Ltd."},
	{ value : "JKCEMENT", label : "J.K. Cement Ltd."},
	{ value : "JKLAKSHMI", label : "JK Lakshmi Cement Ltd."},
	{ value : "JKPAPER", label : "JK Paper Ltd."},
	{ value : "JMFINANCIL", label : "JM Financial Ltd."},
	{ value : "JSWENERGY", label : "JSW Energy Ltd."},
	{ value : "JSWSTEEL", label : "JSW Steel Ltd."},
	{ value : "JAMNAAUTO", label : "Jamna Auto Industries Ltd."},
	{ value : "JSL", label : "Jindal Stainless Ltd."},
	{ value : "JINDALSTEL", label : "Jindal Steel & Power Ltd."},
	{ value : "JUBLFOOD", label : "Jubilant Foodworks Ltd."},
	{ value : "JUBLINGREA", label : "Jubilant Ingrevia Ltd."},
	{ value : "JUBLPHARMA", label : "Jubilant Pharmova Ltd."},
	{ value : "JUSTDIAL", label : "Justdial Ltd."},
	{ value : "JYOTHYLAB", label : "Jyothy Labs Ltd."},
	{ value : "KPRMILL", label : "K.P.R. Mill Ltd."},
	{ value : "KEI", label : "KEI Industries Ltd."},
	{ value : "KNRCON", label : "KNR Constructions Ltd."},
	{ value : "KPITTECH", label : "KPIT Technologies Ltd."},
	{ value : "KRBL", label : "KRBL Ltd."},
	{ value : "KAJARIACER", label : "Kajaria Ceramics Ltd."},
	{ value : "KALPATPOWR", label : "Kalpataru Power Transmission Ltd."},
	{ value : "KALYANKJIL", label : "Kalyan Jewellers India Ltd."},
	{ value : "KANSAINER", label : "Kansai Nerolac Paints Ltd."},
	{ value : "KARURVYSYA", label : "Karur Vysya Bank Ltd."},
	{ value : "KEC", label : "Kec International Ltd."},
	{ value : "KOTAKBANK", label : "Kotak Mahindra Bank Ltd."},
	{ value : "KIMS", label : "Krishna Institute of Medical Sciences Ltd."},
	{ value : "L&TFH", label : "L&T Finance Holdings Ltd."},
	{ value : "LTTS", label : "L&T Technology Services Ltd."},
	{ value : "LICHSGFIN", label : "LIC Housing Finance Ltd."},
	{ value : "LAXMIMACH", label : "Lakshmi Machine Works Ltd."},
	{ value : "LTI", label : "Larsen & Toubro Infotech Ltd."},
	{ value : "LT", label : "Larsen & Toubro Ltd."},
	{ value : "LATENTVIEW", label : "Latent View Analytics Ltd."},
	{ value : "LAURUSLABS", label : "Laurus Labs Ltd."},
	{ value : "LXCHEM", label : "Laxmi Organic Industries Ltd."},
	{ value : "LINDEINDIA", label : "Linde India Ltd."},
	{ value : "LUPIN", label : "Lupin Ltd."},
	{ value : "LUXIND", label : "Lux Industries Ltd."},
	{ value : "MMTC", label : "MMTC Ltd."},
	{ value : "MOIL", label : "MOIL Ltd."},
	{ value : "MRF", label : "MRF Ltd."},
	{ value : "MTARTECH", label : "MTAR Technologies Ltd."},
	{ value : "LODHA", label : "Macrotech Developers Ltd."},
	{ value : "MGL", label : "Mahanagar Gas Ltd."},
	{ value : "M&MFIN", label : "Mahindra & Mahindra Financial Services Ltd."},
	{ value : "M&M", label : "Mahindra & Mahindra Ltd."},
	{ value : "MAHINDCIE", label : "Mahindra CIE Automotive Ltd."},
	{ value : "MHRIL", label : "Mahindra Holidays & Resorts India Ltd."},
	{ value : "MAHLOG", label : "Mahindra Logistics Ltd."},
	{ value : "MANAPPURAM", label : "Manappuram Finance Ltd."},
	{ value : "MRPL", label : "Mangalore Refinery & Petrochemicals Ltd."},
	{ value : "MARICO", label : "Marico Ltd."},
	{ value : "MARUTI", label : "Maruti Suzuki India Ltd."},
	{ value : "MASTEK", label : "Mastek Ltd."},
	{ value : "MFSL", label : "Max Financial Services Ltd."},
	{ value : "MAXHEALTH", label : "Max Healthcare Institute Ltd."},
	{ value : "MAZDOCK", label : "Mazagoan Dock Shipbuilders Ltd."},
	{ value : "MEDPLUS", label : "Medplus Health Services Ltd."},
	{ value : "METROBRAND", label : "Metro Brands Ltd."},
	{ value : "METROPOLIS", label : "Metropolis Healthcare Ltd."},
	{ value : "MINDTREE", label : "MindTree Ltd."},
	{ value : "MINDAIND", label : "Minda Industries Ltd."},
	{ value : "MOTILALOFS", label : "Motilal Oswal Financial Services Ltd."},
	{ value : "MPHASIS", label : "MphasiS Ltd."},
	{ value : "MCX", label : "Multi Commodity Exchange of India Ltd."},
	{ value : "MUTHOOTFIN", label : "Muthoot Finance Ltd."},
	{ value : "NATCOPHARM", label : "NATCO Pharma Ltd."},
	{ value : "NBCC", label : "NBCC (India) Ltd."},
	{ value : "NCC", label : "NCC Ltd."},
	{ value : "NESCO", label : "NESCO Ltd."},
	{ value : "NHPC", label : "NHPC Ltd."},
	{ value : "NLCINDIA", label : "NLC India Ltd."},
	{ value : "NMDC", label : "NMDC Ltd."},
	{ value : "NOCIL", label : "NOCIL Ltd."},
	{ value : "NTPC", label : "NTPC Ltd."},
	{ value : "NH", label : "Narayana Hrudayalaya Ltd."},
	{ value : "NATIONALUM", label : "National Aluminium Co. Ltd."},
	{ value : "NAVINFLUOR", label : "Navin Fluorine International Ltd."},
	{ value : "NAZARA", label : "Nazara Technologies Ltd."},
	{ value : "NESTLEIND", label : "Nestle India Ltd."},
	{ value : "NETWORK18", label : "Network18 Media & Investments Ltd."},
	{ value : "NAM-INDIA", label : "Nippon Life India Asset Management Ltd."},
	{ value : "NUVOCO", label : "Nuvoco Vistas Corporation Ltd."},
	{ value : "OBEROIRLTY", label : "Oberoi Realty Ltd."},
	{ value : "ONGC", label : "Oil & Natural Gas Corporation Ltd."},
	{ value : "OIL", label : "Oil India Ltd."},
	{ value : "PAYTM", label : "One 97 Communications Ltd."},
	{ value : "OFSS", label : "Oracle Financial Services Software Ltd."},
	{ value : "ORIENTELEC", label : "Orient Electric Ltd."},
	{ value : "POLICYBZR", label : "PB Fintech Ltd."},
	{ value : "PCBL", label : "PCBL Ltd."},
	{ value : "PIIND", label : "PI Industries Ltd."},
	{ value : "PNBHOUSING", label : "PNB Housing Finance Ltd."},
	{ value : "PNCINFRA", label : "PNC Infratech Ltd."},
	{ value : "PVR", label : "PVR Ltd."},
	{ value : "PAGEIND", label : "Page Industries Ltd."},
	{ value : "PERSISTENT", label : "Persistent Systems Ltd."},
	{ value : "PETRONET", label : "Petronet LNG Ltd."},
	{ value : "PFIZER", label : "Pfizer Ltd."},
	{ value : "PHOENIXLTD", label : "Phoenix Mills Ltd."},
	{ value : "PIDILITIND", label : "Pidilite Industries Ltd."},
	{ value : "PEL", label : "Piramal Enterprises Ltd."},
	{ value : "POLYMED", label : "Poly Medicure Ltd."},
	{ value : "POLYCAB", label : "Polycab India Ltd."},
	{ value : "POLYPLEX", label : "Polyplex Corporation Ltd."},
	{ value : "POONAWALLA", label : "Poonawalla Fincorp Ltd."},
	{ value : "PFC", label : "Power Finance Corporation Ltd."},
	{ value : "POWERGRID", label : "Power Grid Corporation of India Ltd."},
	{ value : "PRAJIND", label : "Praj Industries Ltd."},
	{ value : "PRESTIGE", label : "Prestige Estates Projects Ltd."},
	{ value : "PRINCEPIPE", label : "Prince Pipes and Fittings Ltd."},
	{ value : "PRSMJOHNSN", label : "Prism Johnson Ltd."},
	{ value : "PRIVISCL", label : "Privi Speciality Chemicals Ltd."},
	{ value : "PGHL", label : "Procter & Gamble Health Ltd."},
	{ value : "PGHH", label : "Procter & Gamble Hygiene & Health Care Ltd."},
	{ value : "PNB", label : "Punjab National Bank"},
	{ value : "QUESS", label : "Quess Corp Ltd."},
	{ value : "RBLBANK", label : "RBL Bank Ltd."},
	{ value : "RECLTD", label : "REC Ltd."},
	{ value : "RHIM", label : "RHI MAGNESITA INDIA LTD."},
	{ value : "RITES", label : "RITES Ltd."},
	{ value : "RADICO", label : "Radico Khaitan Ltd"},
	{ value : "RVNL", label : "Rail Vikas Nigam Ltd."},
	{ value : "RAILTEL", label : "Railtel Corporation Of India Ltd."},
	{ value : "RAIN", label : "Rain Industries Ltd"},
	{ value : "RAJESHEXPO", label : "Rajesh Exports Ltd."},
	{ value : "RALLIS", label : "Rallis India Ltd."},
	{ value : "RCF", label : "Rashtriya Chemicals & Fertilizers Ltd."},
	{ value : "RATNAMANI", label : "Ratnamani Metals & Tubes Ltd."},
	{ value : "RTNINDIA", label : "RattanIndia Enterprises Ltd."},
	{ value : "REDINGTON", label : "Redington (India) Ltd."},
	{ value : "RELAXO", label : "Relaxo Footwears Ltd."},
	{ value : "RELIANCE", label : "Reliance Industries Ltd."},
	{ value : "RBA", label : "Restaurant Brands Asia Ltd."},
	{ value : "ROSSARI", label : "Rossari Biotech Ltd."},
	{ value : "ROUTE", label : "Route Mobile Ltd."},
	{ value : "SBICARD", label : "SBI Cards and Payment Services Ltd."},
	{ value : "SBILIFE", label : "SBI Life Insurance Company Ltd."},
	{ value : "SIS", label : "SIS Ltd."},
	{ value : "SJVN", label : "SJVN Ltd."},
	{ value : "SKFINDIA", label : "SKF India Ltd."},
	{ value : "SRF", label : "SRF Ltd."},
	{ value : "SANOFI", label : "Sanofi India Ltd."},
	{ value : "SAPPHIRE", label : "Sapphire Foods India Ltd."},
	{ value : "SAREGAMA", label : "Saregama India Ltd"},
	{ value : "SCHAEFFLER", label : "Schaeffler India Ltd."},
	{ value : "SEQUENT", label : "Sequent Scientific Ltd."},
	{ value : "SFL", label : "Sheela Foam Ltd."},
	{ value : "SHILPAMED", label : "Shilpa Medicare Ltd."},
	{ value : "SCI", label : "Shipping Corporation of India Ltd."},
	{ value : "SHREECEM", label : "Shree Cement Ltd."},
	{ value : "RENUKA", label : "Shree Renuka Sugars Ltd."},
	{ value : "SHRIRAMCIT", label : "Shriram City Union Finance Ltd."},
	{ value : "SRTRANSFIN", label : "Shriram Transport Finance Co. Ltd."},
	{ value : "SHYAMMETL", label : "Shyam Metalics and Energy Ltd."},
	{ value : "SIEMENS", label : "Siemens Ltd."},
	{ value : "SOBHA", label : "Sobha Ltd."},
	{ value : "SOLARINDS", label : "Solar Industries India Ltd."},
	{ value : "SOLARA", label : "Solara Active Pharma Sciences Ltd."},
	{ value : "SONACOMS", label : "Sona BLW Precision Forgings Ltd."},
	{ value : "SONATSOFTW", label : "Sonata Software Ltd."},
	{ value : "SPICEJET", label : "Spicejet Ltd."},
	{ value : "STARHEALTH", label : "Star Health and Allied Insurance Company Ltd."},
	{ value : "SBIN", label : "State Bank of India"},
	{ value : "SAIL", label : "Steel Authority of India Ltd."},
	{ value : "SWSOLAR", label : "Sterling and Wilson Renewable Energy Ltd."},
	{ value : "STLTECH", label : "Sterlite Technologies Ltd."},
	{ value : "STAR", label : "Strides Pharma Science Ltd."},
	{ value : "SUDARSCHEM", label : "Sudarshan Chemical Industries Ltd."},
	{ value : "SUMICHEM", label : "Sumitomo Chemical India Ltd."},
	{ value : "SPARC", label : "Sun Pharma Advanced Research Company Ltd."},
	{ value : "SUNPHARMA", label : "Sun Pharmaceutical Industries Ltd."},
	{ value : "SUNTV", label : "Sun TV Network Ltd."},
	{ value : "SUNDARMFIN", label : "Sundaram Finance Ltd."},
	{ value : "SUNDRMFAST", label : "Sundram Fasteners Ltd."},
	{ value : "SUNTECK", label : "Sunteck Realty Ltd."},
	{ value : "SUPRAJIT", label : "Suprajit Engineering Ltd."},
	{ value : "SUPREMEIND", label : "Supreme Industries Ltd."},
	{ value : "SUVENPHAR", label : "Suven Pharmaceuticals Ltd."},
	{ value : "SUZLON", label : "Suzlon Energy Ltd."},
	{ value : "SYMPHONY", label : "Symphony Ltd."},
	{ value : "SYNGENE", label : "Syngene International Ltd."},
	{ value : "TCIEXP", label : "TCI Express Ltd."},
	{ value : "TCNSBRANDS", label : "TCNS Clothing Co. Ltd."},
	{ value : "TTKPRESTIG", label : "TTK Prestige Ltd."},
	{ value : "TV18BRDCST", label : "TV18 Broadcast Ltd."},
	{ value : "TVSMOTOR", label : "TVS Motor Company Ltd."},
	{ value : "TANLA", label : "Tanla Platforms Ltd."},
	{ value : "TATACHEM", label : "Tata Chemicals Ltd."},
	{ value : "TATACOFFEE", label : "Tata Coffee Ltd."},
	{ value : "TATACOMM", label : "Tata Communications Ltd."},
	{ value : "TCS", label : "Tata Consultancy Services Ltd."},
	{ value : "TATACONSUM", label : "Tata Consumer Products Ltd."},
	{ value : "TATAELXSI", label : "Tata Elxsi Ltd."},
	{ value : "TATAINVEST", label : "Tata Investment Corporation Ltd."},
	{ value : "TATAMTRDVR", label : "Tata Motors Ltd DVR"},
	{ value : "TATAMOTORS", label : "Tata Motors Ltd."},
	{ value : "TATAPOWER", label : "Tata Power Co. Ltd."},
	{ value : "TATASTLLP", label : "Tata Steel Long Products Ltd."},
	{ value : "TATASTEEL", label : "Tata Steel Ltd."},
	{ value : "TTML", label : "Tata Teleservices (Maharashtra) Ltd."},
	{ value : "TEAMLEASE", label : "Teamlease Services Ltd."},
	{ value : "TECHM", label : "Tech Mahindra Ltd."},
	{ value : "NIACL", label : "The New India Assurance Company Ltd."},
	{ value : "RAMCOCEM", label : "The Ramco Cements Ltd."},
	{ value : "THERMAX", label : "Thermax Ltd."},
	{ value : "THYROCARE", label : "Thyrocare Technologies Ltd."},
	{ value : "TIMKEN", label : "Timken India Ltd."},
	{ value : "TITAN", label : "Titan Company Ltd."},
	{ value : "TORNTPHARM", label : "Torrent Pharmaceuticals Ltd."},
	{ value : "TORNTPOWER", label : "Torrent Power Ltd."},
	{ value : "TRENT", label : "Trent Ltd."},
	{ value : "TRIDENT", label : "Trident Ltd."},
	{ value : "TRIVENI", label : "Triveni Engineering & Industries Ltd."},
	{ value : "TRITURBINE", label : "Triveni Turbine Ltd."},
	{ value : "TIINDIA", label : "Tube Investments of India Ltd."},
	{ value : "UCOBANK", label : "UCO Bank"},
	{ value : "UFLEX", label : "UFLEX Ltd."},
	{ value : "UPL", label : "UPL Ltd."},
	{ value : "UTIAMC", label : "UTI Asset Management Company Ltd."},
	{ value : "ULTRACEMCO", label : "UltraTech Cement Ltd."},
	{ value : "UNIONBANK", label : "Union Bank of India"},
	{ value : "UBL", label : "United Breweries Ltd."},
	{ value : "MCDOWELL-N", label : "United Spirits Ltd."},
	{ value : "VGUARD", label : "V-Guard Industries Ltd."},
	{ value : "VMART", label : "V-Mart Retail Ltd."},
	{ value : "VIPIND", label : "V.I.P. Industries Ltd."},
	{ value : "VAIBHAVGBL", label : "Vaibhav Global Ltd."},
	{ value : "VAKRANGEE", label : "Vakrangee Ltd."},
	{ value : "VTL", label : "Vardhman Textiles Ltd."},
	{ value : "VARROC", label : "Varroc Engineering Ltd."},
	{ value : "VBL", label : "Varun Beverages Ltd."},
	{ value : "VEDL", label : "Vedanta Ltd."},
	{ value : "VENKEYS", label : "Venky's (India) Ltd."},
	{ value : "VIJAYA", label : "Vijaya Diagnostic Centre Ltd."},
	{ value : "VINATIORGA", label : "Vinati Organics Ltd."},
	{ value : "IDEA", label : "Vodafone Idea Ltd."},
	{ value : "VOLTAS", label : "Voltas Ltd."},
	{ value : "WELCORP", label : "Welspun Corp Ltd."},
	{ value : "WELSPUNIND", label : "Welspun India Ltd."},
	{ value : "WESTLIFE", label : "Westlife Development Ltd."},
	{ value : "WHIRLPOOL", label : "Whirlpool of India Ltd."},
	{ value : "WIPRO", label : "Wipro Ltd."},
	{ value : "WOCKPHARMA", label : "Wockhardt Ltd."},
	{ value : "YESBANK", label : "Yes Bank Ltd."},
	{ value : "ZFCVINDIA", label : "ZF Commercial Vehicle Control Systems India Ltd."},
	{ value : "ZEEL", label : "Zee Entertainment Enterprises Ltd."},
	{ value : "ZENSARTECH", label : "Zensar Technolgies Ltd."},
	{ value : "ZOMATO", label : "Zomato Ltd."},
	{ value : "ZYDUSLIFE", label : "Zydus Lifesciences Ltd."},
	{ value : "ZYDUSWELL", label : "Zydus Wellness Ltd."},
	{ value : "ECLERX", label : "eClerx Services Ltd."},
]
